server:
  port: 9191
spring:
  application:
    name: Montadora API
  datasource:
    url: jdbc:h2:mem:montadora
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
app:
  config:
    variavel: valor da variavel X
    valor1: 500